stages:
  - test
  - deploy

deploy_staging:
  stage: deploy
  before_script:
    - source /etc/profile
    - gem install bundler
    - bundle install --with=deployment --quiet
  script:
    - eval $(ssh-agent -s)
    - ssh-add <(echo -e "$SSH_PRIVATE_KEY")
    - bundle exec cap staging deploy
  environment:
    name: staging
    url: https://_application_name_.cubesystems.lv
  when: manual
  only:
  - master

deploy_production:
  stage: deploy
  before_script:
    - source /etc/profile
    - gem install bundler
    - bundle install --with=deployment --quiet
  script:
    - eval $(ssh-agent -s)
    - ssh-add <(echo -e "$SSH_PRIVATE_KEY")
    - bundle exec cap production deploy
  environment:
    name: production
    url: https://_application_namem
  when: manual
  only:
  - master

rspec:
  stage: test
  before_script:
    - export RAILS_ENV=test
    - export COVERAGE=y
    - export CI=y
    - source $HOME/.rvm/scripts/rvm
    - gem install bundler
    - cp config/example.database.yml config/database.yml
    - cp config/example.secrets.yml config/secrets.yml
    - bundle install --without=development production deployment --quiet
    - rake db:create
    - rake db:migrate
  script:
    - rake spec
    - ssh coverages@coverages.cubesystems.lv mkdir -p public/_application_name_/
    - rsync -a coverage/ coverages@coverages.cubesystems.lv:~/public/_application_name_/$CI_BUILD_REF_NAME/
